title: "AngelScript リファレンス (和訳)"
summary: "AngelScript の公式ドキュメントの日本語訳です。"
topics: ["cpp", "lua", "c"]
published: false
price: 0
chapters:
  - doc_main
  - doc_license
  - doc_overview
  - doc_compile_lib
  - doc_hello_world
  - doc_good_practice
  - doc_understanding_as
  - doc_register_api
  - doc_register_func
  - doc_register_prop
  - doc_register_type
  - doc_strings
  - doc_arrays
  - doc_gc_object
  - doc_generic
  - doc_adv_generic_handle
  - doc_adv_scoped_type
  - doc_adv_single_ref_type
  - doc_adv_class_hierarchy
  - doc_adv_var_type
  - doc_adv_template
  - doc_adv_weakref
  - doc_cpp_exceptions
  - doc_debug
  - doc_adv_timeout
  - doc_gc
  - doc_adv_multithread
  - doc_adv_concurrent
  - doc_adv_coroutine
  - doc_adv_import
  - doc_adv_dynamic_build
  - doc_adv_precompile
  - doc_finetuning
  - doc_adv_access_mask
  - doc_adv_namespace
  - doc_adv_dynamic_config
  - doc_adv_custom_options
  - doc_adv_reflection
  - doc_serialization
  - doc_adv_inheritappclass
  - doc_call_script_func
  - doc_adv_jit
  - doc_compile_script
  - doc_callbacks
  - doc_memory
  - doc_module
  - doc_obj_handle
  - doc_as_vs_cpp_types
  - doc_samples
  - doc_using_script_class
  - doc_versions
  - doc_script_datatypes
  - doc_script_global
  - doc_script_function
  - doc_script_class
  - doc_script_class_ops
  - doc_script_class_prop
  - doc_script_statement
  - doc_script_expr
  - doc_script_handle
  - doc_script_mixin
  - doc_script_shared
  - doc_script_reserved
  - doc_script_precedence
  - doc_script_stdlib
  - doc_addon
