title: "AngelScript リファレンス (和訳)"
summary: "AngelScript の公式ドキュメントの日本語訳です。"
topics: ["cpp", "lua", "c"]
published: false
price: 0
chapters:
  - doc_main
  - doc_license
  - doc_overview
  - doc_compile_lib
  - doc_hello_world
  - doc_good_practice
  - doc_understanding_as
  - doc_register_api
  - doc_register_func
  - doc_register_prop
  - doc_register_type
  - doc_strings
  - doc_arrays
  - doc_gc_object
  - doc_generic
  - doc_adv_generic_handle
  - doc_adv_scoped_type
  - doc_adv_single_ref_type
  - doc_adv_class_hierarchy
  - doc_adv_var_type
  - doc_adv_template
  - doc_adv_weakref
  - doc_cpp_exceptions
  - doc_debug
  - doc_adv_timeout
  - doc_gc
  - doc_adv_multithread
  - doc_adv_concurrent
  - doc_adv_coroutine
  - doc_adv_import
  - doc_adv_dynamic_build
  - doc_adv_precompile
  - doc_finetuning
  - doc_adv_access_mask
  - doc_adv_namespace
  - doc_adv_dynamic_config
  - doc_adv_custom_options
  - doc_adv_reflection
  - doc_serialization
  - doc_adv_inheritappclass
